# Generated by Django 3.1.1 on 2020-09-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TexTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Template Name')),
                ('upload_date', models.DateTimeField(verbose_name='Date uploaded')),
                ('downloads', models.IntegerField(default=0, verbose_name='Downloads')),
            ],
        ),
    ]
