# Generated by Django 3.1.1 on 2020-09-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TexTemplate',
        ),
    ]
